// Aetheris\aetheris-protocol\contracts\ProfitDistributor.sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// Aetheris\aetheris-protocol\contracts\ProfitDistributor.sol

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";

/**
 * @title ProfitDistributor
 * @notice Tracks user deposits and distributes arbitrage profits proportionally
 *
 * @dev HOW PROFIT DISTRIBUTION WORKS:
 *
 *      Users deposit USDC into this contract. Their deposit entitles them to
 *      a proportional share of all profits generated by Agent Alpha.
 *
 *      The distribution uses a "reward per share" accumulator pattern.
 *      This is the same pattern used by Synthetix, Sushiswap, and most
 *      professional yield protocols. It allows O(1) profit calculation
 *      regardless of how many users are deposited.
 *
 *      HOW THE ACCUMULATOR WORKS:
 *
 *      There is a global variable called `accProfitPerShare`. Every time
 *      Agent Alpha generates profit, this variable increases by:
 *          profit / totalDeposited
 *
 *      Each user has a `rewardDebt` that records the value of accProfitPerShare
 *      at the time they last interacted. Their claimable profit at any moment is:
 *          (deposit * accProfitPerShare) - rewardDebt
 *
 *      This means profits accumulate silently for all users simultaneously,
 *      without requiring any per-user transaction.
 *
 *      EXAMPLE:
 *        User A deposits 1000 USDC. User B deposits 3000 USDC. Total = 4000.
 *        Agent Alpha generates 400 USDC profit.
 *        accProfitPerShare increases by 400/4000 = 0.1
 *        User A can claim: 1000 * 0.1 = 100 USDC (25% of pool = 25% of profit)
 *        User B can claim: 3000 * 0.1 = 300 USDC (75% of pool = 75% of profit)
 *
 *      AUTO-COMPOUND:
 *        Users can choose to have their profits automatically re-deposited,
 *        increasing their principal and therefore their future profit share.
 *
 *      FRONTEND-FACING VIEW FUNCTIONS:
 *        getUserInfo(address)       → deposited, claimableProfit, totalClaimed (single call)
 *        totalValueLocked()         → total USDC currently deposited across all users
 *        totalProfitDistributed()   → total USDC profit ever claimed by users
 *
 * @custom:security-contact security@aetheris.io
 */
contract ProfitDistributor is ReentrancyGuard, AccessControl, Pausable {
    using SafeERC20 for IERC20;

    /*//////////////////////////////////////////////////////////////
                                ROLES
    //////////////////////////////////////////////////////////////*/

    bytes32 public constant AGENT_ROLE    = keccak256("AGENT_ROLE");
    bytes32 public constant GUARDIAN_ROLE = keccak256("GUARDIAN_ROLE");

    /*//////////////////////////////////////////////////////////////
                                EVENTS
    //////////////////////////////////////////////////////////////*/

    event Deposited(address indexed user, uint256 amount, uint256 newTotalDeposit);
    event Withdrawn(address indexed user, uint256 amount, uint256 remainingDeposit);
    event ProfitClaimed(address indexed user, uint256 amount);
    event ProfitCompounded(address indexed user, uint256 amount, uint256 newDeposit);
    event ProfitRecorded(uint256 amount, uint256 newAccProfitPerShare, uint256 totalDeposited);
    event AutoCompoundSet(address indexed user, bool enabled);

    /*//////////////////////////////////////////////////////////////
                                ERRORS
    //////////////////////////////////////////////////////////////*/

    error InsufficientDeposit(uint256 available, uint256 requested);
    error NoProfitToClaim();
    error ZeroAmount();
    error ZeroAddress();
    error NotAgentAlpha();
    error DepositTokenNotSet();

    /*//////////////////////////////////////////////////////////////
                                STRUCTS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Per-user deposit and profit tracking record
     * @param depositAmount   Current deposited amount
     * @param rewardDebt      Accumulated profit already accounted for
     *                        (prevents double-counting past profits)
     * @param totalClaimed    Lifetime profit claimed by this user
     * @param autoCompound    Whether profits auto-reinvest into deposit
     * @param depositedAt     Timestamp of first deposit (for analytics)
     */
    struct UserInfo {
        uint256 depositAmount;
        uint256 rewardDebt;
        uint256 totalClaimed;
        bool    autoCompound;
        uint256 depositedAt;
    }

    /*//////////////////////////////////////////////////////////////
                            STATE VARIABLES
    //////////////////////////////////////////////////////////////*/

    /// @notice The token users deposit (USDC on Base: 6 decimals)
    IERC20 public depositToken;

    /// @notice Accumulated profit per deposited unit — scaled by PRECISION
    uint256 public accProfitPerShare;

    /// @notice Precision multiplier for accProfitPerShare calculations
    uint256 public constant PRECISION = 1e18;

    /// @notice Total amount currently deposited across all users
    uint256 public totalDeposited;

    /// @notice Total profit ever recorded from Agent Alpha
    uint256 public totalProfitRecorded;

    /// @notice Total profit ever claimed by users
    uint256 public totalProfitClaimed;

    /// @notice Per-user info
    mapping(address => UserInfo) public userInfo;

    /// @notice All depositor addresses (for enumeration)
    address[] public depositors;
    mapping(address => bool) public isDepositor;

    /// @notice Minimum deposit amount (prevents dust deposits)
    uint256 public minDepositAmount = 10 * 1e6; // $10 USDC minimum

    /// @notice Maximum deposit per user (prevents whale dominance)
    uint256 public maxDepositPerUser = 1_000_000 * 1e6; // $1M USDC maximum

    /*//////////////////////////////////////////////////////////////
                            CONSTRUCTOR
    //////////////////////////////////////////////////////////////*/

    /**
     * @param _depositToken  USDC token address on Base
     * @param agentAlpha     AgentAlpha contract address (AGENT_ROLE)
     * @param guardian       Guardian address
     * @param governance     Governance timelock address
     */
    constructor(
        address _depositToken,
        address agentAlpha,
        address guardian,
        address governance
    ) {
        if (_depositToken == address(0)) revert ZeroAddress();
        if (agentAlpha    == address(0)) revert ZeroAddress();
        if (guardian      == address(0)) revert ZeroAddress();
        if (governance    == address(0)) revert ZeroAddress();

        depositToken = IERC20(_depositToken);

        _grantRole(DEFAULT_ADMIN_ROLE, governance);
        _grantRole(AGENT_ROLE,         agentAlpha);
        _grantRole(GUARDIAN_ROLE,      guardian);
    }

    /*//////////////////////////////////////////////////////////////
                        USER FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Deposit USDC to earn a share of arbitrage profits
     * @dev Before depositing, settle any pending profit for the user
     *      so that new deposits don't retroactively earn past profits.
     *
     * @param amount  Amount of deposit token to deposit
     */
    function deposit(uint256 amount) external nonReentrant whenNotPaused {
        if (amount < minDepositAmount) revert ZeroAmount();

        UserInfo storage user = userInfo[msg.sender];

        // Settle pending profit before changing deposit amount
        if (user.depositAmount > 0) {
            uint256 pending = _pendingProfit(msg.sender);
            if (pending > 0) {
                if (user.autoCompound) {
                    _compound(msg.sender, pending);
                } else {
                    _transferProfit(msg.sender, pending);
                }
            }
        }

        depositToken.safeTransferFrom(msg.sender, address(this), amount);

        user.depositAmount += amount;
        user.rewardDebt     = (user.depositAmount * accProfitPerShare) / PRECISION;
        if (user.depositedAt == 0) user.depositedAt = block.timestamp;

        totalDeposited += amount;

        if (!isDepositor[msg.sender]) {
            isDepositor[msg.sender] = true;
            depositors.push(msg.sender);
        }

        emit Deposited(msg.sender, amount, user.depositAmount);
    }

    /**
     * @notice Withdraw deposited USDC
     * @dev Settles pending profit before withdrawal.
     *
     * @param amount  Amount to withdraw (must be <= deposit balance)
     */
    function withdraw(uint256 amount) external nonReentrant {
        UserInfo storage user = userInfo[msg.sender];
        if (amount > user.depositAmount) {
            revert InsufficientDeposit(user.depositAmount, amount);
        }
        if (amount == 0) revert ZeroAmount();

        uint256 pending = _pendingProfit(msg.sender);
        if (pending > 0) {
            if (user.autoCompound) {
                _compound(msg.sender, pending);
            } else {
                _transferProfit(msg.sender, pending);
            }
        }

        user.depositAmount -= amount;
        user.rewardDebt     = (user.depositAmount * accProfitPerShare) / PRECISION;

        totalDeposited -= amount;

        depositToken.safeTransfer(msg.sender, amount);

        emit Withdrawn(msg.sender, amount, user.depositAmount);
    }

    /**
     * @notice Claim all pending profit without withdrawing deposit
     */
    function claimProfit() external nonReentrant whenNotPaused {
        uint256 pending = _pendingProfit(msg.sender);
        if (pending == 0) revert NoProfitToClaim();

        UserInfo storage user = userInfo[msg.sender];
        user.rewardDebt = (user.depositAmount * accProfitPerShare) / PRECISION;

        _transferProfit(msg.sender, pending);
    }

    /**
     * @notice Manually compound pending profit into deposit
     */
    function compound() external nonReentrant whenNotPaused {
        uint256 pending = _pendingProfit(msg.sender);
        if (pending == 0) revert NoProfitToClaim();

        UserInfo storage user = userInfo[msg.sender];
        _compound(msg.sender, pending);
        user.rewardDebt = (user.depositAmount * accProfitPerShare) / PRECISION;
    }

    /**
     * @notice Enable or disable automatic compounding
     */
    function setAutoCompound(bool enabled) external {
        uint256 pending = _pendingProfit(msg.sender);
        if (pending > 0) {
            UserInfo storage user = userInfo[msg.sender];
            if (user.autoCompound) {
                _compound(msg.sender, pending);
            } else {
                _transferProfit(msg.sender, pending);
            }
            user.rewardDebt = (user.depositAmount * accProfitPerShare) / PRECISION;
        }

        userInfo[msg.sender].autoCompound = enabled;
        emit AutoCompoundSet(msg.sender, enabled);
    }

    /*//////////////////////////////////////////////////////////////
                    AGENT ALPHA — PROFIT RECORDING
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Record profit from Agent Alpha and update the accumulator
     * @dev Called by AgentAlpha after a successful arbitrage trade.
     *      The profit tokens must have already been transferred to this contract.
     *
     * @param token   Token in which profit was earned
     * @param amount  Amount of profit
     */
    function recordProfit(address token, uint256 amount)
        external
        onlyRole(AGENT_ROLE)
    {
        if (amount == 0) revert ZeroAmount();
        if (address(depositToken) != token) return;

        if (totalDeposited == 0) {
            // No depositors — profit stays in contract as protocol reserve
            return;
        }

        accProfitPerShare   += (amount * PRECISION) / totalDeposited;
        totalProfitRecorded += amount;

        emit ProfitRecorded(amount, accProfitPerShare, totalDeposited);
    }

    /*//////////////////////////////////////////////////////////////
                        INTERNAL HELPERS
    //////////////////////////////////////////////////////////////*/

    function _pendingProfit(address userAddr) internal view returns (uint256) {
        UserInfo storage user = userInfo[userAddr];
        if (user.depositAmount == 0) return 0;
        uint256 accumulated = (user.depositAmount * accProfitPerShare) / PRECISION;
        if (accumulated <= user.rewardDebt) return 0;
        return accumulated - user.rewardDebt;
    }

    function _transferProfit(address userAddr, uint256 amount) internal {
        userInfo[userAddr].totalClaimed += amount;
        totalProfitClaimed             += amount;
        depositToken.safeTransfer(userAddr, amount);
        emit ProfitClaimed(userAddr, amount);
    }

    function _compound(address userAddr, uint256 amount) internal {
        UserInfo storage user = userInfo[userAddr];
        user.depositAmount  += amount;
        user.totalClaimed   += amount;
        totalDeposited      += amount;
        totalProfitClaimed  += amount;
        emit ProfitCompounded(userAddr, amount, user.depositAmount);
    }

    /*//////////////////////////////////////////////////////////////
                        VIEW FUNCTIONS
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Returns all data the frontend needs for a user in a single call.
     * @dev    Avoids three separate RPC calls from the frontend. Returns values
     *         denominated in deposit token units (USDC: 6 decimals).
     *
     * @param  user             Address to query
     * @return deposited        Current USDC deposit balance
     * @return claimableProfit  Unclaimed profit available right now
     * @return totalClaimed     Lifetime profit claimed by this user
     */
    function getUserInfo(address user)
        external
        view
        returns (
            uint256 deposited,
            uint256 claimableProfit,
            uint256 totalClaimed
        )
    {
        UserInfo storage u = userInfo[user];
        deposited       = u.depositAmount;
        claimableProfit = _pendingProfit(user);
        totalClaimed    = u.totalClaimed;
    }

    /**
     * @notice Total USDC currently deposited across all users.
     * @dev    Alias for `totalDeposited`. Exposed under this name to match
     *         the standard DeFi TVL convention expected by the frontend ABI.
     */
    function totalValueLocked() external view returns (uint256) {
        return totalDeposited;
    }

    /**
     * @notice Total USDC profit ever paid out to users (claimed or compounded).
     * @dev    Alias for `totalProfitClaimed`. Exposed under this name to match
     *         the frontend ABI for the stats banner on the Earn page.
     */
    function totalProfitDistributed() external view returns (uint256) {
        return totalProfitClaimed;
    }

    /// @notice Current claimable profit for a user
    function pendingProfit(address userAddr) external view returns (uint256) {
        return _pendingProfit(userAddr);
    }

    /// @notice User's current deposit balance
    function depositBalance(address userAddr) external view returns (uint256) {
        return userInfo[userAddr].depositAmount;
    }

    /// @notice User's lifetime claimed profit
    function lifetimeClaimed(address userAddr) external view returns (uint256) {
        return userInfo[userAddr].totalClaimed;
    }

    /// @notice User's share of the pool as a fraction (scaled by 1e18)
    function userPoolShare(address userAddr) external view returns (uint256) {
        if (totalDeposited == 0) return 0;
        return (userInfo[userAddr].depositAmount * PRECISION) / totalDeposited;
    }

    /// @notice Total number of unique depositors
    function depositorCount() external view returns (uint256) {
        return depositors.length;
    }

    /// @notice APY estimate based on cumulative profit (annualized, in basis points)
    function estimatedAPYBps() external view returns (uint256) {
        if (totalDeposited == 0) return 0;
        uint256 dailyProfit = totalProfitRecorded / (
            (block.timestamp - (block.timestamp % 1 days) + 1 days) / 1 days
        );
        return (dailyProfit * 365 * 10_000) / totalDeposited;
    }

    /*//////////////////////////////////////////////////////////////
                            ADMIN
    //////////////////////////////////////////////////////////////*/

    function setMinDeposit(uint256 amount) external onlyRole(DEFAULT_ADMIN_ROLE) {
        minDepositAmount = amount;
    }

    function setMaxDepositPerUser(uint256 amount) external onlyRole(DEFAULT_ADMIN_ROLE) {
        maxDepositPerUser = amount;
    }

    function pause()   external onlyRole(GUARDIAN_ROLE) { _pause(); }
    function unpause() external onlyRole(GUARDIAN_ROLE) { _unpause(); }
}
